export const explorersList = [
  {
    id: 1,
    chain_id: '0x1',
    name: 'Etherscan',
    url: 'https://etherscan.io',
    chain: 'Ethereum',
    logo: 'https://etherscan.io/images/favicon3.ico',
    tags: ['Etheruem', 'Mainnet'],
  },
  {
    id: 5,
    chain_id: '0x5',
    name: 'Etherscan',
    url: 'https://goerli.etherscan.io',
    chain: 'Ethereum',
    logo: 'https://etherscan.io/images/favicon3.ico',
    tags: ['Etheruem', 'Testnet', 'Goerli'],
  },
  {
    id: 11155111,
    chain_id: '0xaa36a7',
    name: 'Etherscan',
    url: 'https://sepolia.etherscan.io',
    chain: 'Ethereum',
    logo: 'https://etherscan.io/images/favicon3.ico',
    tags: ['Etheruem', 'Testnet', 'Sepolia'],
  },
  {
    id: 56,
    chain_id: '0x38',
    name: 'BNB Chain',
    url: 'https://bscscan.com',
    chain: 'BSC',
    logo: 'https://bscscan.com/images/favicon.ico',
    tags: ['BNB Chain', 'Mainnet'],
  },
  {
    id: 10,
    chain_id: '0xa',
    name: 'Optimism',
    url: 'https://optimistic.etherscan.io',
    chain: 'Optimism',
    logo: 'https://optimistic.etherscan.io/images/favicon.ico',
    tags: ['Optimism', 'Mainnet'],
  },
  {
    id: 42161,
    chain_id: '0xa4b1',
    name: 'Arbitrum One',
    url: 'https://arbiscan.io',
    chain: 'Arbitrum',
    logo: 'https://arbiscan.io/images/favicon.ico',
    tags: ['Arbitrum', 'Mainnet'],
  },
  {
    id: 137,
    chain_id: '0x89',
    name: 'Polygon',
    url: 'https://polygonscan.com',
    chain: 'Polygon',
    logo: 'https://polygonscan.com/images/favicon.ico',
    tags: ['Polygon', 'Mainnet'],
  },
  {
    id: 43114,
    chain_id: '0xa86a',
    name: 'Avalanche',
    url: 'https://snowtrace.io',
    chain: 'Avalanache',
    logo: 'https://snowtrace.io/images/favicon.ico',
    tags: ['Avalanche', 'Mainnet'],
  },
  {
    id: 250,
    chain_id: '0xfa',
    name: 'Fantom',
    url: 'https://ftmscan.com',
    chain: 'Fantom',
    logo: 'https://ftmscan.com/images/favicon.png',
    tags: ['Fantom', 'Mainnet'],
  },
  {
    id: 25,
    chain_id: '0x19',
    name: 'Cronos',
    url: 'https://cronoscan.com',
    chain: 'Cronos',
    logo: 'https://cronoscan.com/images/favicon.png',
    tags: ['Cronos', 'Mainnet'],
  },
]
